tasks/urls.py
from django.urls import path

import tasks.views
from .views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    change_task_status
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("add/", TaskCreateView.as_view(), name="task-add"),
    path("<int:pk>", change_task_status, name="change-task-status"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/add", TagCreateView.as_view(), name="tag-add"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),

]

app_name = "tasks"

todo_list/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

todo_list_mate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),

]

tasks/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f"{self.name}"


class Task(models.Model):
    content = models.CharField(max_length=255, unique=True)
    created = models.DateTimeField(auto_now=True)
    deadline = models.DateTimeField(blank=True)
    status = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:

        ordering = ["status", "-created"]

    def __str__(self):
        return f"{self.content}"



tasks/forms.py
from django import forms
from django.forms import SelectDateWidget

from tasks.models import Tag, Task


class TaskCreationForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateField(widget=SelectDateWidget(empty_label=("year", "month", "day")), required=False)

    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")


class TaskUpdateForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    deadline = forms.DateField(widget=SelectDateWidget(empty_label=("year", "month", "day")), required=False)

    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")

tasks/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views import generic

from tasks.forms import TaskCreationForm, TaskUpdateForm
from tasks.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = Task.objects.all().prefetch_related("tags")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm
    success_url = reverse_lazy("tasks:task-list")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskCreationForm
    success_url = reverse_lazy("tasks:task-list")


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")


def change_task_status(request, pk):
    task = Task.objects.get(id=pk)
    task.status = not task.status
    task.save()
    return redirect(reverse("tasks:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>TODO List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}
        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
{#  {% if user.is_authenticated %}#}
{#    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>#}
{#    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>#}
{#  {% else %}#}
{#    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>#}
{#  {% endif %}#}
{##}
{#  <br>#}
  <li class="list-group-item"><a href="{% url 'tasks:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:tag-list' %}">Tags</a></li>

</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you want to delete "{{ tag.name }}" tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'tasks:tag-list' %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Add" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
  <br>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a href="{% url 'tasks:tag-add' %}" class="btn btn-primary link-to-page">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
              {{ tag.name }}
          </td>
          <td>
              <a href="{% url 'tasks:tag-update' pk=tag.id %}" class = "btn btn-secondary">
                Update
              </a>
            </td>
            <td>
              <a href="{% url 'tasks:tag-delete' pk=tag.id %}" class = "btn btn-secondary">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you want to delete "{{ task.content }}" task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'tasks:task-list' %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Add" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    TODO list
    <a href="{% url 'tasks:task-add' %}" class="btn btn-primary link-to-page">
        Add task
    </a>
  </h1>
  <br>
  {% if task_list %}
    {% for task in task_list %}
      <h4>
          <strong>{{ task.content}} </strong>
          {% if task.status %}
              <span style="color:green">Completed</span>
              <a href="{% url 'tasks:change-task-status' pk=task.id%}" class="btn btn-secondary link-to-page">
              Undo
              </a>
          {% else %}
              <span style="color:red">Not done</span>
              <a href="{% url 'tasks:change-task-status' pk=task.id %}" class="btn btn-success link-to-page">
              Complete
              </a>
          {% endif %}

      </h4>
      <p>Created: {{ task.created }}</p>
      <p>
          Tags: {% for tag in task.tags.all %}{{ tag.name }} {% endfor %}
          <a href="{% url 'tasks:task-update' pk=task.id %} ">Update</a>
          <a href="{% url 'tasks:task-delete' pk=task.id %} ">Delete</a>
      </p>
      <hr>
  {% endfor %}
  {% else %}
    <p>There are no tasks in the list</p>
  {% endif %}
{% endblock %}